on: [push, pull_request]

# on:
#   push:
#     branches: ["master"]
#   pull_request:
#     branches: ["master"]

name: Test tokio

env:
  RUSTFLAGS: -Dwarnings
  nightly: nightly-2020-01-25

jobs:
  test_tokio:
    name: Test tokio full
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@master

      # Run `tokio` with only `full`
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ${{ github.workspace }}/tokio/Cargo.toml --features full
        env:
          RUST_BACKTRACE: 1
          CI: 'True'
        name: tokio - cargo test --features full

      # Run `tokio` with "unstable" cfg flag
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ${{ github.workspace }}/tokio/Cargo.toml --features full
        env:
          RUSTFLAGS: '--cfg tokio_unstable'
          RUST_BACKTRACE: 1
          CI: 'True'
        name: tokio - cargo test --features full

  test_cross_subcrates:
    name: Test ${{ matrix.crate }} (${{ matrix.os }}) all-features
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        crate:
          - tokio
          - tests-integration
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@master

      # Run with all crate features
      - name: ${{ matrix.crate }} - cargo test --features full
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ${{ github.workspace }}/${{ matrix.crate }}/Cargo.toml --all-features
        env:
          RUST_BACKTRACE: 1
          CI: 'True'

        # Check benches
      - name: ${{ matrix.crate }} - cargo check --benches
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path ${{ github.workspace }}/${{ matrix.crate }}/Cargo.toml --all-features --benches
        env:
          RUST_BACKTRACE: 1
          CI: 'True'

      - name: Patch Cargo.toml
        shell: bash
        run: |
          set -e

          # Remove any existing patch statements
          mv Cargo.toml Cargo.toml.bck
          sed -n '/\[patch.crates-io\]/q;p' Cargo.toml.bck > Cargo.toml

          # Patch all crates
          cat ci/patch.toml >> Cargo.toml

          # Print `Cargo.toml` for debugging
          echo "~~~~ Cargo.toml ~~~~"
          cat Cargo.toml
          echo "~~~~~~~~~~~~~~~~~~~~"

      # Run with all crate features
      - name: ${{ matrix.crate }} - cargo test --features full
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ${{ github.workspace }}/${{ matrix.crate }}/Cargo.toml --all-features
        env:
          RUST_BACKTRACE: 1
          CI: 'True'


  test_subcrates:
    name: Test ${{ matrix.crate }} all-features
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate:
          - tokio-macros
          - tokio-test
          - tokio-util
          - examples
    steps:
      - uses: actions/checkout@master

      # Run with all crate features
      - name: ${{ matrix.crate }} - cargo test --all-features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ${{ github.workspace }}/${{ matrix.crate }}/Cargo.toml --all-features
        env:
          RUST_BACKTRACE: 1
          CI: 'True'

        # Check benches
      - name: ${{ matrix.crate }} - cargo check --benches
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path ${{ github.workspace }}/${{ matrix.crate }}/Cargo.toml --all-features --benches
        env:
          RUST_BACKTRACE: 1
          CI: 'True'

      - name: Patch Cargo.toml
        shell: bash
        run: |
          set -e

          # Remove any existing patch statements
          mv Cargo.toml Cargo.toml.bck
          sed -n '/\[patch.crates-io\]/q;p' Cargo.toml.bck > Cargo.toml

          # Patch all crates
          cat ci/patch.toml >> Cargo.toml

          # Print `Cargo.toml` for debugging
          echo "~~~~ Cargo.toml ~~~~"
          cat Cargo.toml
          echo "~~~~~~~~~~~~~~~~~~~~"

      # Run with all crate features
      - name: ${{ matrix.crate }} - cargo test --all-features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ${{ github.workspace }}/${{ matrix.crate }}/Cargo.toml --all-features
        env:
          RUST_BACKTRACE: 1
          CI: 'True'

  test_integration:
    name: Integration tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@master
      - run: cargo install cargo-hack
        name: Install cargo-hack
      - uses: actions-rs/cargo@v1
        name: cargo hack test --each-feature
        with:
          command: hack
          args: test --manifest-path ${{ github.workspace }}/tests-integration/Cargo.toml --each-feature
        env:
          CI: 'True'
